package com.transglobe.cf.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2018-01-15T17:00:15.515+08:00
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://webservice.cf.transglobe.com/", name = "CFService")
@XmlSeeAlso({com.transglobe.cf.webservice.bean.ObjectFactory.class, ObjectFactory.class, com.transglobe.cf.webservice.bean.request.ObjectFactory.class})
public interface CFService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "downloadWithIndex", targetNamespace = "http://webservice.cf.transglobe.com/", className = "com.transglobe.cf.webservice.DownloadWithIndex")
    @WebMethod
    @ResponseWrapper(localName = "downloadWithIndexResponse", targetNamespace = "http://webservice.cf.transglobe.com/", className = "com.transglobe.cf.webservice.DownloadWithIndexResponse")
    public com.transglobe.cf.webservice.DownloadResponse downloadWithIndex(
        @WebParam(name = "user", targetNamespace = "")
        java.lang.String user,
        @WebParam(name = "reportId", targetNamespace = "")
        java.lang.String reportId,
        @WebParam(name = "squeezeDate", targetNamespace = "")
        com.transglobe.cf.webservice.SqueezeDate squeezeDate,
        @WebParam(name = "onlyLastVersion", targetNamespace = "")
        java.lang.String onlyLastVersion,
        @WebParam(name = "queryIndex", targetNamespace = "")
        com.transglobe.cf.webservice.bean.request.Clause queryIndex,
        @WebParam(name = "onlyBookmarkSection", targetNamespace = "")
        java.lang.String onlyBookmarkSection,
        @WebParam(name = "isRelease", targetNamespace = "")
        java.lang.String isRelease,
        @WebParam(name = "projectCode", targetNamespace = "")
        java.lang.String projectCode
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "downloadWithGuid", targetNamespace = "http://webservice.cf.transglobe.com/", className = "com.transglobe.cf.webservice.DownloadWithGuid")
    @WebMethod
    @ResponseWrapper(localName = "downloadWithGuidResponse", targetNamespace = "http://webservice.cf.transglobe.com/", className = "com.transglobe.cf.webservice.DownloadWithGuidResponse")
    public com.transglobe.cf.webservice.DownloadResponse downloadWithGuid(
        @WebParam(name = "user", targetNamespace = "")
        java.lang.String user,
        @WebParam(name = "guidList", targetNamespace = "")
        java.util.List<java.lang.String> guidList,
        @WebParam(name = "merge", targetNamespace = "")
        java.lang.String merge,
        @WebParam(name = "zip", targetNamespace = "")
        java.lang.String zip,
        @WebParam(name = "zipPassword", targetNamespace = "")
        java.lang.String zipPassword,
        @WebParam(name = "onlyBookmarkSection", targetNamespace = "")
        java.lang.String onlyBookmarkSection,
        @WebParam(name = "projectCode", targetNamespace = "")
        java.lang.String projectCode
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateReleaseDate", targetNamespace = "http://webservice.cf.transglobe.com/", className = "com.transglobe.cf.webservice.UpdateReleaseDate")
    @WebMethod
    @ResponseWrapper(localName = "updateReleaseDateResponse", targetNamespace = "http://webservice.cf.transglobe.com/", className = "com.transglobe.cf.webservice.UpdateReleaseDateResponse")
    public com.transglobe.cf.webservice.Response updateReleaseDate(
        @WebParam(name = "user", targetNamespace = "")
        java.lang.String user,
        @WebParam(name = "guidList", targetNamespace = "")
        java.util.List<java.lang.String> guidList,
        @WebParam(name = "releaseDate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar releaseDate,
        @WebParam(name = "projectCode", targetNamespace = "")
        java.lang.String projectCode
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "archiveFile", targetNamespace = "http://webservice.cf.transglobe.com/", className = "com.transglobe.cf.webservice.ArchiveFile")
    @WebMethod
    @ResponseWrapper(localName = "archiveFileResponse", targetNamespace = "http://webservice.cf.transglobe.com/", className = "com.transglobe.cf.webservice.ArchiveFileResponse")
    public com.transglobe.cf.webservice.ArchiveResponse archiveFile(
        @WebParam(name = "user", targetNamespace = "")
        java.lang.String user,
        @WebParam(name = "overWriteOption", targetNamespace = "")
        java.lang.String overWriteOption,
        @WebParam(name = "repeatArchive", targetNamespace = "")
        java.lang.String repeatArchive,
        @WebParam(name = "archiveContent", targetNamespace = "")
        com.transglobe.cf.webservice.Content archiveContent,
        @WebParam(name = "isRelease", targetNamespace = "")
        java.lang.String isRelease,
        @WebParam(name = "projectCode", targetNamespace = "")
        java.lang.String projectCode
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryWithGuid", targetNamespace = "http://webservice.cf.transglobe.com/", className = "com.transglobe.cf.webservice.QueryWithGuid")
    @WebMethod
    @ResponseWrapper(localName = "queryWithGuidResponse", targetNamespace = "http://webservice.cf.transglobe.com/", className = "com.transglobe.cf.webservice.QueryWithGuidResponse")
    public com.transglobe.cf.webservice.QueryResponse queryWithGuid(
        @WebParam(name = "user", targetNamespace = "")
        java.lang.String user,
        @WebParam(name = "guidList", targetNamespace = "")
        java.util.List<java.lang.String> guidList,
        @WebParam(name = "projectCode", targetNamespace = "")
        java.lang.String projectCode
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryWithIndex", targetNamespace = "http://webservice.cf.transglobe.com/", className = "com.transglobe.cf.webservice.QueryWithIndex")
    @WebMethod
    @ResponseWrapper(localName = "queryWithIndexResponse", targetNamespace = "http://webservice.cf.transglobe.com/", className = "com.transglobe.cf.webservice.QueryWithIndexResponse")
    public com.transglobe.cf.webservice.QueryResponse queryWithIndex(
        @WebParam(name = "user", targetNamespace = "")
        java.lang.String user,
        @WebParam(name = "reportIdList", targetNamespace = "")
        java.util.List<java.lang.String> reportIdList,
        @WebParam(name = "squeezeDate", targetNamespace = "")
        com.transglobe.cf.webservice.SqueezeDate squeezeDate,
        @WebParam(name = "onlyLastVersion", targetNamespace = "")
        java.lang.String onlyLastVersion,
        @WebParam(name = "queryIndex", targetNamespace = "")
        com.transglobe.cf.webservice.bean.request.Clause queryIndex,
        @WebParam(name = "sort", targetNamespace = "")
        com.transglobe.cf.webservice.Sort sort,
        @WebParam(name = "page", targetNamespace = "")
        java.lang.Integer page,
        @WebParam(name = "pageSize", targetNamespace = "")
        java.lang.Integer pageSize,
        @WebParam(name = "isRelease", targetNamespace = "")
        java.lang.String isRelease,
        @WebParam(name = "projectCode", targetNamespace = "")
        java.lang.String projectCode
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateLastVersionMark", targetNamespace = "http://webservice.cf.transglobe.com/", className = "com.transglobe.cf.webservice.UpdateLastVersionMark")
    @WebMethod
    @ResponseWrapper(localName = "updateLastVersionMarkResponse", targetNamespace = "http://webservice.cf.transglobe.com/", className = "com.transglobe.cf.webservice.UpdateLastVersionMarkResponse")
    public com.transglobe.cf.webservice.Response updateLastVersionMark(
        @WebParam(name = "user", targetNamespace = "")
        java.lang.String user,
        @WebParam(name = "guid", targetNamespace = "")
        java.lang.String guid,
        @WebParam(name = "projectCode", targetNamespace = "")
        java.lang.String projectCode
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteWithGuid", targetNamespace = "http://webservice.cf.transglobe.com/", className = "com.transglobe.cf.webservice.DeleteWithGuid")
    @WebMethod
    @ResponseWrapper(localName = "deleteWithGuidResponse", targetNamespace = "http://webservice.cf.transglobe.com/", className = "com.transglobe.cf.webservice.DeleteWithGuidResponse")
    public com.transglobe.cf.webservice.DeleteResponse deleteWithGuid(
        @WebParam(name = "user", targetNamespace = "")
        java.lang.String user,
        @WebParam(name = "guid", targetNamespace = "")
        java.lang.String guid,
        @WebParam(name = "deleteAllVersion", targetNamespace = "")
        java.lang.String deleteAllVersion,
        @WebParam(name = "projectCode", targetNamespace = "")
        java.lang.String projectCode
    );
}
