package com.transglobe.cf.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2018-01-15T17:00:15.531+08:00
 * Generated source version: 3.0.3
 * 
 */
@WebServiceClient(name = "CFServiceService", 
                  wsdlLocation = "file:/C:/SIP/cfg/CFServiceNew.xml",
                  targetNamespace = "http://webservice.cf.transglobe.com/") 
public class CFServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.cf.transglobe.com/", "CFServiceService");
    public final static QName CFServicePort = new QName("http://webservice.cf.transglobe.com/", "CFServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/SIP/cfg/CFServiceNew.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CFServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/SIP/cfg/CFServiceNew.xml");
        }
        WSDL_LOCATION = url;
    }

    public CFServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CFServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CFServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CFService
     */
    @WebEndpoint(name = "CFServicePort")
    public CFService getCFServicePort() {
        return super.getPort(CFServicePort, CFService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CFService
     */
    @WebEndpoint(name = "CFServicePort")
    public CFService getCFServicePort(WebServiceFeature... features) {
        return super.getPort(CFServicePort, CFService.class, features);
    }

}
