
package com.transglobe.cf.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2018-01-15T17:00:15.437+08:00
 * Generated source version: 3.0.3
 * 
 */
public final class CFService_CFServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.cf.transglobe.com/", "CFServiceService");

    private CFService_CFServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CFServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CFServiceService ss = new CFServiceService(wsdlURL, SERVICE_NAME);
        CFService port = ss.getCFServicePort();  
        
        {
        System.out.println("Invoking downloadWithIndex...");
        java.lang.String _downloadWithIndex_user = "";
        java.lang.String _downloadWithIndex_reportId = "";
        com.transglobe.cf.webservice.SqueezeDate _downloadWithIndex_squeezeDate = null;
        java.lang.String _downloadWithIndex_onlyLastVersion = "";
        com.transglobe.cf.webservice.bean.request.Clause _downloadWithIndex_queryIndex = null;
        java.lang.String _downloadWithIndex_onlyBookmarkSection = "";
        java.lang.String _downloadWithIndex_isRelease = "";
        java.lang.String _downloadWithIndex_projectCode = "";
        com.transglobe.cf.webservice.DownloadResponse _downloadWithIndex__return = port.downloadWithIndex(_downloadWithIndex_user, _downloadWithIndex_reportId, _downloadWithIndex_squeezeDate, _downloadWithIndex_onlyLastVersion, _downloadWithIndex_queryIndex, _downloadWithIndex_onlyBookmarkSection, _downloadWithIndex_isRelease, _downloadWithIndex_projectCode);
        System.out.println("downloadWithIndex.result=" + _downloadWithIndex__return);


        }
        {
        System.out.println("Invoking downloadWithGuid...");
        java.lang.String _downloadWithGuid_user = "";
        java.util.List<java.lang.String> _downloadWithGuid_guidList = null;
        java.lang.String _downloadWithGuid_merge = "";
        java.lang.String _downloadWithGuid_zip = "";
        java.lang.String _downloadWithGuid_zipPassword = "";
        java.lang.String _downloadWithGuid_onlyBookmarkSection = "";
        java.lang.String _downloadWithGuid_projectCode = "";
        com.transglobe.cf.webservice.DownloadResponse _downloadWithGuid__return = port.downloadWithGuid(_downloadWithGuid_user, _downloadWithGuid_guidList, _downloadWithGuid_merge, _downloadWithGuid_zip, _downloadWithGuid_zipPassword, _downloadWithGuid_onlyBookmarkSection, _downloadWithGuid_projectCode);
        System.out.println("downloadWithGuid.result=" + _downloadWithGuid__return);


        }
        {
        System.out.println("Invoking updateReleaseDate...");
        java.lang.String _updateReleaseDate_user = "";
        java.util.List<java.lang.String> _updateReleaseDate_guidList = null;
        javax.xml.datatype.XMLGregorianCalendar _updateReleaseDate_releaseDate = null;
        java.lang.String _updateReleaseDate_projectCode = "";
        com.transglobe.cf.webservice.Response _updateReleaseDate__return = port.updateReleaseDate(_updateReleaseDate_user, _updateReleaseDate_guidList, _updateReleaseDate_releaseDate, _updateReleaseDate_projectCode);
        System.out.println("updateReleaseDate.result=" + _updateReleaseDate__return);


        }
        {
        System.out.println("Invoking archiveFile...");
        java.lang.String _archiveFile_user = "";
        java.lang.String _archiveFile_overWriteOption = "";
        java.lang.String _archiveFile_repeatArchive = "";
        com.transglobe.cf.webservice.Content _archiveFile_archiveContent = null;
        java.lang.String _archiveFile_isRelease = "";
        java.lang.String _archiveFile_projectCode = "";
        com.transglobe.cf.webservice.ArchiveResponse _archiveFile__return = port.archiveFile(_archiveFile_user, _archiveFile_overWriteOption, _archiveFile_repeatArchive, _archiveFile_archiveContent, _archiveFile_isRelease, _archiveFile_projectCode);
        System.out.println("archiveFile.result=" + _archiveFile__return);


        }
        {
        System.out.println("Invoking queryWithGuid...");
        java.lang.String _queryWithGuid_user = "";
        java.util.List<java.lang.String> _queryWithGuid_guidList = null;
        java.lang.String _queryWithGuid_projectCode = "";
        com.transglobe.cf.webservice.QueryResponse _queryWithGuid__return = port.queryWithGuid(_queryWithGuid_user, _queryWithGuid_guidList, _queryWithGuid_projectCode);
        System.out.println("queryWithGuid.result=" + _queryWithGuid__return);


        }
        {
        System.out.println("Invoking queryWithIndex...");
        java.lang.String _queryWithIndex_user = "";
        java.util.List<java.lang.String> _queryWithIndex_reportIdList = null;
        com.transglobe.cf.webservice.SqueezeDate _queryWithIndex_squeezeDate = null;
        java.lang.String _queryWithIndex_onlyLastVersion = "";
        com.transglobe.cf.webservice.bean.request.Clause _queryWithIndex_queryIndex = null;
        com.transglobe.cf.webservice.Sort _queryWithIndex_sort = null;
        java.lang.Integer _queryWithIndex_page = null;
        java.lang.Integer _queryWithIndex_pageSize = null;
        java.lang.String _queryWithIndex_isRelease = "";
        java.lang.String _queryWithIndex_projectCode = "";
        com.transglobe.cf.webservice.QueryResponse _queryWithIndex__return = port.queryWithIndex(_queryWithIndex_user, _queryWithIndex_reportIdList, _queryWithIndex_squeezeDate, _queryWithIndex_onlyLastVersion, _queryWithIndex_queryIndex, _queryWithIndex_sort, _queryWithIndex_page, _queryWithIndex_pageSize, _queryWithIndex_isRelease, _queryWithIndex_projectCode);
        System.out.println("queryWithIndex.result=" + _queryWithIndex__return);


        }
        {
        System.out.println("Invoking updateLastVersionMark...");
        java.lang.String _updateLastVersionMark_user = "";
        java.lang.String _updateLastVersionMark_guid = "";
        java.lang.String _updateLastVersionMark_projectCode = "";
        com.transglobe.cf.webservice.Response _updateLastVersionMark__return = port.updateLastVersionMark(_updateLastVersionMark_user, _updateLastVersionMark_guid, _updateLastVersionMark_projectCode);
        System.out.println("updateLastVersionMark.result=" + _updateLastVersionMark__return);


        }
        {
        System.out.println("Invoking deleteWithGuid...");
        java.lang.String _deleteWithGuid_user = "";
        java.lang.String _deleteWithGuid_guid = "";
        java.lang.String _deleteWithGuid_deleteAllVersion = "";
        java.lang.String _deleteWithGuid_projectCode = "";
        com.transglobe.cf.webservice.DeleteResponse _deleteWithGuid__return = port.deleteWithGuid(_deleteWithGuid_user, _deleteWithGuid_guid, _deleteWithGuid_deleteAllVersion, _deleteWithGuid_projectCode);
        System.out.println("deleteWithGuid.result=" + _deleteWithGuid__return);


        }

        System.exit(0);
    }

}
