package com.tgl.esp.ws.server.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2017-04-19T18:47:15.208+08:00
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://service.server.ws.esp.tgl.com/", name = "MailManagementWS")
@XmlSeeAlso({ObjectFactory.class})
public interface MailManagementWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "retrieveStaticMailGroupMemberByID", targetNamespace = "http://service.server.ws.esp.tgl.com/", className = "com.tgl.esp.ws.server.service.RetrieveStaticMailGroupMemberByID")
    @WebMethod
    @ResponseWrapper(localName = "retrieveStaticMailGroupMemberByIDResponse", targetNamespace = "http://service.server.ws.esp.tgl.com/", className = "com.tgl.esp.ws.server.service.RetrieveStaticMailGroupMemberByIDResponse")
    public com.tgl.esp.ws.server.service.MailGroupMemberResponse retrieveStaticMailGroupMemberByID(
        @WebParam(name = "arg0", targetNamespace = "")
        com.tgl.esp.ws.server.service.MailGroupMemberRequest arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRawTemplateByID", targetNamespace = "http://service.server.ws.esp.tgl.com/", className = "com.tgl.esp.ws.server.service.GetRawTemplateByID")
    @WebMethod
    @ResponseWrapper(localName = "getRawTemplateByIDResponse", targetNamespace = "http://service.server.ws.esp.tgl.com/", className = "com.tgl.esp.ws.server.service.GetRawTemplateByIDResponse")
    public com.tgl.esp.ws.server.service.TemplateContentResponse getRawTemplateByID(
        @WebParam(name = "arg0", targetNamespace = "")
        com.tgl.esp.ws.server.service.RawTemplateContentRequest arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTransferedTemplateByID", targetNamespace = "http://service.server.ws.esp.tgl.com/", className = "com.tgl.esp.ws.server.service.GetTransferedTemplateByID")
    @WebMethod
    @ResponseWrapper(localName = "getTransferedTemplateByIDResponse", targetNamespace = "http://service.server.ws.esp.tgl.com/", className = "com.tgl.esp.ws.server.service.GetTransferedTemplateByIDResponse")
    public com.tgl.esp.ws.server.service.TemplateContentResponse getTransferedTemplateByID(
        @WebParam(name = "arg0", targetNamespace = "")
        com.tgl.esp.ws.server.service.TemplateContentRequest arg0
    );
}
