
package com.tgl.esp.ws.server.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2017-04-19T18:47:15.146+08:00
 * Generated source version: 3.0.3
 * 
 */
public final class MailManagementWS_MailManagementWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.server.ws.esp.tgl.com/", "MailManagementWSService");

    private MailManagementWS_MailManagementWSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MailManagementWSService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MailManagementWSService ss = new MailManagementWSService(wsdlURL, SERVICE_NAME);
        MailManagementWS port = ss.getMailManagementWSPort();  
        
        {
        System.out.println("Invoking retrieveStaticMailGroupMemberByID...");
        com.tgl.esp.ws.server.service.MailGroupMemberRequest _retrieveStaticMailGroupMemberByID_arg0 = null;
        com.tgl.esp.ws.server.service.MailGroupMemberResponse _retrieveStaticMailGroupMemberByID__return = port.retrieveStaticMailGroupMemberByID(_retrieveStaticMailGroupMemberByID_arg0);
        System.out.println("retrieveStaticMailGroupMemberByID.result=" + _retrieveStaticMailGroupMemberByID__return);


        }
        {
        System.out.println("Invoking getRawTemplateByID...");
        com.tgl.esp.ws.server.service.RawTemplateContentRequest _getRawTemplateByID_arg0 = null;
        com.tgl.esp.ws.server.service.TemplateContentResponse _getRawTemplateByID__return = port.getRawTemplateByID(_getRawTemplateByID_arg0);
        System.out.println("getRawTemplateByID.result=" + _getRawTemplateByID__return);


        }
        {
        System.out.println("Invoking getTransferedTemplateByID...");
        com.tgl.esp.ws.server.service.TemplateContentRequest _getTransferedTemplateByID_arg0 = null;
        com.tgl.esp.ws.server.service.TemplateContentResponse _getTransferedTemplateByID__return = port.getTransferedTemplateByID(_getTransferedTemplateByID_arg0);
        System.out.println("getTransferedTemplateByID.result=" + _getTransferedTemplateByID__return);


        }

        System.exit(0);
    }

}
