package com.tgl.common.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2017-04-19T18:47:06.994+08:00
 * Generated source version: 3.0.3
 * 
 */
@WebServiceClient(name = "CommonWSService", 
                  wsdlLocation = "file:/c:/sip/cfg/ebao.xml",
                  targetNamespace = "http://tgl.com/common/ws/") 
public class CommonWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tgl.com/common/ws/", "CommonWSService");
    public final static QName CommonWSServicePort = new QName("http://tgl.com/common/ws/", "CommonWSServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/c:/sip/cfg/ebao.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CommonWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/c:/sip/cfg/ebao.xml");
        }
        WSDL_LOCATION = url;
    }

    public CommonWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CommonWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommonWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CommonWS
     */
    @WebEndpoint(name = "CommonWSServicePort")
    public CommonWS getCommonWSServicePort() {
        return super.getPort(CommonWSServicePort, CommonWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommonWS
     */
    @WebEndpoint(name = "CommonWSServicePort")
    public CommonWS getCommonWSServicePort(WebServiceFeature... features) {
        return super.getPort(CommonWSServicePort, CommonWS.class, features);
    }

}
