package com.tgl.common.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2017-04-19T18:47:06.979+08:00
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://tgl.com/common/ws/", name = "CommonWS")
@XmlSeeAlso({ObjectFactory.class})
public interface CommonWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "exchange", targetNamespace = "http://tgl.com/common/ws/", className = "com.tgl.common.ws.Exchange")
    @WebMethod
    @ResponseWrapper(localName = "exchangeResponse", targetNamespace = "http://tgl.com/common/ws/", className = "com.tgl.common.ws.ExchangeResponse")
    public com.tgl.common.ws.StandardResponse exchange(
        @WebParam(name = "arg0", targetNamespace = "")
        com.tgl.common.ws.StandardRequest arg0
    );
}
